#image: crobox/clickhouse-scala-client-build:latest
image: mozilla/docker-sbt:latest

services:
  - clickhouse/clickhouse-server:21.1.7.1

variables:
  # Configure caching rules for gitlab
  #  SBT_OPTS: "-Dsbt.override.build.repos=true -Dsbt.ivy.home=/cache/.ivy2/ -Divy.home=/cache/.ivy2/ -Dfile.encoding=UTF8 -Djava.awt.headless=true"
  SBT_OPTS: "'set resolvers += \"Sonatype OSS Snapshots\" at \"https://oss.sonatype.org/content/repositories/snapshots\"'"
  CI_JOB: ""
  SBT_PROJECT_NAME: "clickhouse-scala-client"
  CLICKHOUSE_HOST: "clickhouse"
  OPENJDK_TAG: "11.0.13"
  SBT_VERSION: "1:5:7"

stages:
  - build

#before_script:
#  - SERVICE_NAME_COMPOSE=`echo $SBT_PROJECT_NAME | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]//g'`
#  - export COMPOSE_PROJECT_NAME="${SERVICE_NAME_COMPOSE}${CI_PIPELINE_ID}"
#  - NETWORK_NAME="${COMPOSE_PROJECT_NAME}_default"
#  - docker-compose up -d
#  - docker network connect $NETWORK_NAME ${GITLAB_CI_CONTAINER_ID}

#after_script:
#  - SERVICE_NAME_COMPOSE=`echo $SBT_PROJECT_NAME | tr '[:upper:]' '[:lower:]' | sed 's/[^a-zA-Z0-9]//g'`
#  - export COMPOSE_PROJECT_NAME="${SERVICE_NAME_COMPOSE}${CI_PIPELINE_ID}"
#  - NETWORK_NAME="${COMPOSE_PROJECT_NAME}_default"
#  - docker network disconnect $NETWORK_NAME ${GITLAB_CI_CONTAINER_ID}
#  - docker-compose down -v --remove-orphans

unit:test:
  stage: build
  script:
    - sbt clean coverage test coverageReport
    - sbt coverageAggregate
  artifacts:
    when: always
    reports:
      cobertura: target/*/coverage-report/cobertura.xml
      junit: ./**/target/test-reports/TEST-*.xml

integration:test:
  stage: build
  script:
    - export CONTAINER_HOSTNAME=`hostname -i | cut -d ' ' -f 1`
    - sbt clean coverage dsl/it:test coverageReport
    - sbt coverageAggregate
  artifacts:
    when: always
    reports:
      cobertura: target/*/coverage-report/cobertura.xml
      junit: ./**/target/test-reports/TEST-*.xml