sudo: required

language: scala
scala:
  - 2.12.11
  - 2.13.3
jdk: openjdk11
env:
  - CLICKHOUSE_VERSION=19.13.1.11
  - CLICKHOUSE_VERSION=20.1.2.4
#  -CLICKHOUSE_VERSION=20.3.12.112

sbt_args: "'set resolvers += \"Sonatype OSS Snapshots\" at \"https://oss.sonatype.org/content/repositories/snapshots\"'"

after_success:
  - >
      test "${TRAVIS_PULL_REQUEST}" = 'false' && test "${TRAVIS_BRANCH}" = 'master' &&
      sbt 'set resolvers += "Sonatype OSS Snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"'
      'set credentials += Credentials("Sonatype Nexus Repository Manager", "oss.sonatype.org", System.getenv("SONATYPE_USER"), System.getenv("SONATYPE_PASS"))'
      ++${TRAVIS_SCALA_VERSION} publish

before_install:
  - docker-compose up -d

services:
  - docker



