version: '3'
services:
  clickhouse:
      # https://hub.docker.com/r/yandex/clickhouse-server/
      image: yandex/clickhouse-server:${CLICKHOUSE_VERSION}
      expose:
        - "8123"
      ports:
        - "8123:8123"
        - "9000:9000"