version: '3'
services:
  clickhouse:
      # https://docs.docker.com/compose/compose-file/#variable-substitution
      #image: "yandex/clickhouse-server:${CLICKHOUSE_VERSION:-20.8.11.17}"
      image: "yandex/clickhouse-server:${CLICKHOUSE_VERSION:-21.1.7.1}"
      expose:
        - "8123"
      ports:
        - "8123:8123"
        - "9000:9000"